## 평가

### MNIST 손글씨 "Is it seven?

In [1]:
import numpy as np
import pandas as pd

In [9]:
from sklearn.base import BaseEstimator
class MyFakeClassifier(BaseEstimator):
    def fit(self, X, Y):      #fit 메소드를 재정의
        pass
    def predict(self, X):
        return np.zeros((X.shape[0], 1), dtype=int)
    

In [2]:
from sklearn.datasets import load_digits

digits = load_digits()
digits.data[0]

array([ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0., 13., 15., 10.,
       15.,  5.,  0.,  0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  4.,
       12.,  0.,  0.,  8.,  8.,  0.,  0.,  5.,  8.,  0.,  0.,  9.,  8.,
        0.,  0.,  4., 11.,  0.,  1., 12.,  7.,  0.,  0.,  2., 14.,  5.,
       10., 12.,  0.,  0.,  0.,  0.,  6., 13., 10.,  0.,  0.,  0.])

In [3]:
digits.target[0]

0

In [25]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    digits.data, digits.target, stratify=digits.target,
    test_size=0.2,random_state=2021
)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((1437, 64), (360, 64), (1437,), (360,))

In [26]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier(random_state=2021)
dtc.fit(X_train, y_train)
dtc_pred = dtc.predict(X_test)

In [27]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, pred)

0.8777777777777778

- MyFakeClassifier

In [13]:
y_test[10:20]

array([0, 2, 5, 5, 8, 1, 6, 2, 5, 7])

In [15]:
y_test.shape

(360,)

In [29]:
y_test = (y_test == 7).astype(int)
y_test

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [21]:
my_clf = MyFakeClassifier()
my_clf.fit(X_train, y_train)
my_pred = my_clf.predict(X_test)
accuracy_score(y_test, my_pred)

0.9

In [ ]:
from sklearn.model_selection import train_test_split

y = (digits.target ==7).astype(int)

X_train, X_test, y_train, y_test = train_test_split(
    digits.data, y, stratify=y,
    test_size=0.2,random_state=2021
)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

### 오차 행렬

In [22]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,my_pred)

array([[324,   0],
       [ 36,   0]], dtype=int64)

In [30]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,dtc_pred)

array([[38, 36, 28, 38, 39, 35, 35,  3, 36, 36],
       [ 0,  0,  0,  0,  1,  0,  0, 32,  2,  1],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0]], dtype=int64)

### 정밀도와 재현율

In [32]:
from sklearn.metrics import precision_score, recall_score
precision_score(y_test,dtc_pred), recall_score(y_test,dtc_pred)

ValueError: Target is multiclass but average='binary'. Please choose another average setting, one of [None, 'micro', 'macro', 'weighted'].