## 0622 과제
### 실제값 y_test, 다중 선형 회귀 예측값, 결정 트리 예측값 데이터프레임 만들기

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
from sklearn.datasets import load_diabetes
diabetes = load_diabetes()
df = pd.DataFrame(diabetes.data, columns = diabetes.feature_names)
df['target'] = diabetes.target
df.head()

age       sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2  0.085299  0.050680  0.044451 -0.005671 -0.045599 -0.034194 -0.032356   
3 -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4  0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   

         s4        s5        s6  target  
0 -0.002592  0.019908 -0.017646   151.0  
1 -0.039493 -0.068330 -0.092204    75.0  
2 -0.002592  0.002864 -0.025930   141.0  
3  0.034309  0.022692 -0.009362   206.0  
4 -0.002592 -0.031991 -0.046641   135.0

- train/test 분리

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
   diabetes.data, diabetes.target, test_size=0.1, random_state=2021
)

In [11]:
# 다중 선형회귀
from sklearn.linear_model import LinearRegression
X = X_train
y = y_train
lr = LinearRegression()
lr.fit(X, y)

LinearRegression()

In [12]:
# 다중 선형회귀 예측값
lr_y_hat = dt.predict(X_test)
lr_y_hat 

array([178., 144., 258., 190., 178.,  47., 225., 144., 118., 214.,  55.,
       214.,  88., 210., 181., 160.,  99., 173., 197., 257., 143.,  42.,
        96.,  55., 275., 274., 150.,  78., 182., 151.,  90., 225.,  73.,
        48.,  94.,  77., 187., 281.,  52., 264., 310., 293., 140., 103.,
        75.])

In [13]:
# 결정트리
from sklearn.tree import DecisionTreeRegressor
X = X_train
y = y_train
dt = DecisionTreeRegressor()
dt.fit(X, y)

DecisionTreeRegressor()

In [14]:
# 결정트리 예측값
dt_y_hat = dt.predict(X_test)
dt_y_hat

array([127., 144., 258., 190., 178.,  47., 173., 127.,  84., 214.,  55.,
       214., 113., 210., 181., 150.,  78., 150., 202., 259., 128.,  42.,
        96.,  63., 275., 274., 168.,  99., 182., 164.,  90., 168., 109.,
        48., 185.,  97., 187., 281.,  78., 243., 310., 259., 140.,  96.,
        66.])

In [15]:
# 실제값
y_test

array([155., 167., 185., 109.,  65.,  77., 277., 244., 148., 102., 200.,
       162.,  59., 147., 216., 144.,  85., 131., 196., 212.,  60., 252.,
       121.,  78., 275., 336., 190., 221., 103., 156., 235., 102., 115.,
       276., 140.,  83.,  95., 151., 141., 128., 217., 170., 110., 191.,
        91.])

In [20]:
df = pd.DataFrame({'y':y_test, 'dt':dt_y_hat, 'lr':lr_y_hat})
df.head()

y     dt     lr
0  155.0  127.0  178.0
1  167.0  144.0  144.0
2  185.0  258.0  258.0
3  109.0  190.0  190.0
4   65.0  178.0  178.0

In [21]:
df

y     dt     lr
0   155.0  127.0  178.0
1   167.0  144.0  144.0
2   185.0  258.0  258.0
3   109.0  190.0  190.0
4    65.0  178.0  178.0
5    77.0   47.0   47.0
6   277.0  173.0  225.0
7   244.0  127.0  144.0
8   148.0   84.0  118.0
9   102.0  214.0  214.0
10  200.0   55.0   55.0
11  162.0  214.0  214.0
12   59.0  113.0   88.0
13  147.0  210.0  210.0
14  216.0  181.0  181.0
15  144.0  150.0  160.0
16   85.0   78.0   99.0
17  131.0  150.0  173.0
18  196.0  202.0  197.0
19  212.0  259.0  257.0
20   60.0  128.0  143.0
21  252.0   42.0   42.0
22  121.0   96.0   96.0
23   78.0   63.0   55.0
24  275.0  275.0  275.0
25  336.0  274.0  274.0
26  190.0  168.0  150.0
27  221.0   99.0   78.0
28  103.0  182.0  182.0
29  156.0  164.0  151.0
30  235.0   90.0   90.0
31  102.0  168.0  225.0
32  115.0  109.0   73.0
33  276.0   48.0   48.0
34  140.0  185.0   94.0
35   83.0   97.0   77.0
36   95.0  187.0  187.0
37  151.0  281.0  281.0
38  141.0   78.0   52.0
39  128.0  243.0  264.0
40  217.0  310.0  310.0
41  170.0  259.0  293.0
42  110.0  140.0  140.0
43  191.0   96.0  103.0
44   91.0   66.0   75.0